version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    restart: always
    ports: 
      - 10000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - api
    networks:
      - tibetan-api

  api:
    container_name: tibetan-api
    build: ./api
    image: tibetan-api
    restart: always
    volumes:
      - ./api/app:/app
    environment: 
      - MONGODB=mongodb://mongodb/tibetan
    depends_on: 
      - mongodb
    command: yarn start
    networks: 
      - tibetan-api

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./mongo/db:/data/db
    networks:
      - tibetan-api

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - tibetan-api

  tibetan-kwic:
    container_name: tibetan-kwic
    image: httpd:2.4-alpine
    restart: always
    volumes:
      - ./kwic/htdocs:/usr/local/apache2/htdocs
      - ./kwic/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8000:80
    networks:
      - tibetan-api

networks:
  tibetan-api: